name: update the feed 
on:
  schedule:
    - cron: '0 4,10,16,22 * * *'
  workflow_dispatch:
jobs:
  update:
    name: digest
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: main
      - name: python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: python things
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run
        env:
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
          MASTODON_BASE_URL: ${{ secrets.MASTODON_BASE_URL }}
        run: |
          python run.py -n 12 -s SimpleWeighted -t lax
